### ISSUE TITLE
sidebar

### ISSUE THREAD

**Issue by ba9uette** [gontrancherrier/maupassant-hexo#1]
글쓴이/책이름 으로 구성해서 볼 수 있도록
각 포스트.md 상단에 있는 yml에 tag와 category를 쓰면
(코드를 전부 다 바꿀 엄두는 안 나고 해서 tag => author, category => book(name) 으로 간주하고 쓰는 것으로...)
```yml
---
title: start
date: 2018-09-15 19:51:22
tags: baguette
category: 우울할 땐 뇌과학
---
```

이럿케 되도록 수정해볼까 하는데 어떠신지들 ... 👀
<img width="290" alt="2018-10-08 03 10 54" src="https://user-images.githubusercontent.com/43289472/46585145-df546780-caa7-11e8-8359-e46724056b38.png">
